package build

import (
	"tool/file"
	"encoding/yaml"
	"strings"
)

_autoGenerated: "AUTOGENERATED - DO NOT EDIT\n\n"

command: genyamlworkflows: {
	for w in workflows {
		"\(w._name)": file.Create & {
			filename: "workflows/\(strings.ToLower(w._name)).yaml"
			contents: "# \(_autoGenerated)\(yaml.Marshal(w.workflow))"
		}
	}
}
